# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-27 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseUniversities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='高校名称')),
                ('competent_authority', models.CharField(max_length=128, verbose_name='管辖部门')),
                ('location', models.CharField(max_length=128, verbose_name='所在地')),
                ('level', models.IntegerField(verbose_name='办学层次')),
                ('style', models.IntegerField(verbose_name='办学类型')),
                ('description', models.TextField(default=None, verbose_name='描述')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '中国全国高校',
                'verbose_name_plural': '中国全国高校',
                'db_table': 'chinese_universities',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ReginoanlManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=128, verbose_name='省')),
                ('city', models.CharField(max_length=128, verbose_name='市区')),
                ('county', models.CharField(max_length=128, verbose_name='区县')),
                ('people', models.CharField(max_length=128, verbose_name='人口数量')),
                ('description', models.TextField(default=None, verbose_name='描述')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '中国区划管理',
                'verbose_name_plural': '中国区划管理',
                'db_table': 'reginoanl_management',
                'ordering': ['-create_time'],
            },
        ),
    ]
