# -*- coding: UTF-8 -*-
"""
Django settings for city project.

Generated by 'django-admin startproject' using Django 1.11.13.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

# Application definition

from .base import *

INSTALLED_APPS += [
    'huntjob',
    "user_manager",
]
