# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-23 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntjob', '0002_cityauthpermission_parent_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityauthpermission',
            name='parent_node',
            field=models.IntegerField(default=0),
        ),
    ]
