# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-27 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntjob', '0004_auto_20180727_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrequirements',
            name='value_max',
            field=models.IntegerField(default=1, verbose_name='最大数'),
        ),
    ]
